const ACCEPT_OFFERS = {
  ACCEPT_OFFERS_PENDING: 'ACCEPT_OFFERS_PENDING',
  ACCEPT_OFFERS_SUCCESS: 'ACCEPT_OFFERS_SUCCESS',
  ACCEPT_OFFERS_ERROR: 'ACCEPT_OFFERS_ERROR',
};

export default ACCEPT_OFFERS;
