const CREATE_PRODUCT = {
  CREATE_PRODUCT_PENDING: 'CREATE_PRODUCT_PENDING',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_ERROR: 'CREATE_PRODUCT_ERROR',
};

export default CREATE_PRODUCT;
