const PRODUCTDETAIL = {
  FETCH_PRODUCT_DETAIL_PENDING: 'FETCH_PRODUCT_DETAIL_PENDING',
  FETCH_PRODUCT_DETAIL_SUCCESS: 'FETCH_PRODUCT_DETAIL_SUCCESS',
  FETCH_PRODUCT_DETAIL_ERROR: 'FETCH_PRODUCT_DETAIL_ERROR',
};

export default PRODUCTDETAIL;
