const PURCHASE = {
  FETCH_PURCHASE_PENDING: 'FETCH_PURCHASE_PENDING',
  FETCH_PURCHASE_SUCCESS: 'FETCH_PURCHASE_SUCCESS',
  FETCH_PURCHASE_ERROR: 'FETCH_PURCHASE_ERROR',
};

export default PURCHASE;
