const PURCHASE = {
  FETCH_PURCHASE_REQUEST: 'FETCH_PURCHASE_REQUEST',
  FETCH_PURCHASE_SUCCESS: 'FETCH_PURCHASE_SUCCESS',
  FETCH_PURCHASE_FAILURE: 'FETCH_PURCHASE_FAILURE',
};

export default PURCHASE;
