const RECEIVED_OFFERS = {
  RECEIVED_OFFERS_PENDING: 'RECEIVED_OFFERS_PENDING',
  RECEIVED_OFFERS_SUCCESS: 'RECEIVED_OFFERS_SUCCESS',
  RECEIVED_OFFERS_ERROR: 'RECEIVED_OFFERS_ERROR',
};

export default RECEIVED_OFFERS;
