const REJECT_OFFERS = {
  REJECT_OFFERS_PENDING: 'REJECT_OFFERS_PENDING',
  REJECT_OFFERS_SUCCESS: 'REJECT_OFFERS_SUCCESS',
  REJECT_OFFERS_ERROR: 'REJECT_OFFERS_ERROR',
};

export default REJECT_OFFERS;
