const UPLOAD_IMAGE = {
  FETCH_UPLOAD_IMAGE_PENDING: 'FETCH_UPLOAD_IMAGE_PENDING',
  FETCH_UPLOAD_IMAGE_SUCCESS: 'FETCH_UPLOAD_IMAGE_SUCCESS',
  FETCH_UPLOAD_IMAGE_DELETE: 'FETCH_UPLOAD_IMAGE_DELETE',
  FETCH_UPLOAD_IMAGE_ERROR: 'FETCH_UPLOAD_IMAGE_ERROR',
  UPLOAD_IMAGE_PROGRESS: 'UPLOAD_IMAGE_PROGRESS',
};

export default UPLOAD_IMAGE;
